-- MySQL Script generated by MySQL Workbench
-- Thu Oct  6 18:31:57 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bdtienda
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdtienda
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdtienda` DEFAULT CHARACTER SET utf8 ;
USE `bdtienda` ;

-- -----------------------------------------------------
-- Table `bdtienda`.`TipoUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdtienda`.`TipoUsuario` (
  `idTipoUsuario` INT NOT NULL AUTO_INCREMENT,
  `NomUsuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdtienda`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdtienda`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Usuario` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Contra` VARCHAR(45) NOT NULL,
  `idTipoUsuario` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  CONSTRAINT `tipouser`
    FOREIGN KEY ()
    REFERENCES `bdtienda`.`TipoUsuario` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdtienda`.`Marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdtienda`.`Marca` (
  `idMarca` INT NOT NULL AUTO_INCREMENT,
  `NombreM` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMarca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdtienda`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdtienda`.`Categoria` (
  `idCategoría` INT NOT NULL,
  `NomCate` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategoría`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdtienda`.`Dispositivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdtienda`.`Dispositivo` (
  `idDispositivo` INT NOT NULL AUTO_INCREMENT,
  `Caracter` TEXT(300) NOT NULL,
  `Precio` FLOAT NOT NULL,
  `Existencia` INT NOT NULL,
  `Descuento` FLOAT NULL,
  `idMarca` INT NOT NULL,
  `idCategoria` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idDispositivo`),
  INDEX `usuario_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `marca`
    FOREIGN KEY ()
    REFERENCES `bdtienda`.`Marca` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `categoria`
    FOREIGN KEY ()
    REFERENCES `bdtienda`.`Categoria` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `bdtienda`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdtienda`.`Compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdtienda`.`Compras` (
  `idCompras` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NOT NULL,
  `CantidadCom` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  `idDispositivo` INT NOT NULL,
  PRIMARY KEY (`idCompras`),
  INDEX `dispo_idx` (`idDispositivo` ASC) VISIBLE,
  INDEX `usuario_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `bdtienda`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `dispo`
    FOREIGN KEY (`idDispositivo`)
    REFERENCES `bdtienda`.`Dispositivo` (`idDispositivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdtienda`.`Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdtienda`.`Venta` (
  `idVenta` INT NOT NULL,
  `FechaV` DATE NOT NULL,
  `CantidadVen` INT NOT NULL,
  `idUsuaio` INT NOT NULL,
  `idDispositivo` INT NOT NULL,
  PRIMARY KEY (`idVenta`),
  INDEX `user_idx` (`idUsuaio` ASC) VISIBLE,
  INDEX `disposi_idx` (`idDispositivo` ASC) VISIBLE,
  CONSTRAINT `user`
    FOREIGN KEY (`idUsuaio`)
    REFERENCES `bdtienda`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `disposi`
    FOREIGN KEY (`idDispositivo`)
    REFERENCES `bdtienda`.`Dispositivo` (`idDispositivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdtienda`.`Encuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdtienda`.`Encuesta` (
  `idPregunta` INT NOT NULL AUTO_INCREMENT,
  `Pregunta` TEXT(300) NOT NULL,
  PRIMARY KEY (`idPregunta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdtienda`.`Respuestas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdtienda`.`Respuestas` (
  `idRespuestas` INT NOT NULL AUTO_INCREMENT,
  `Respuesta` INT NOT NULL,
  `idPregunta` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idRespuestas`),
  INDEX `pregu_idx` (`idPregunta` ASC) VISIBLE,
  INDEX `user_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `pregu`
    FOREIGN KEY (`idPregunta`)
    REFERENCES `bdtienda`.`Encuesta` (`idPregunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `bdtienda`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
